name: flutter_proj
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  laz_flutter_web:
    path: ./plugins/laz_flutter_web
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^3.4.4595
  font_awesome_flutter: ^8.5.0
  tuple: ^1.0.3
  strings: ^0.1.2
  flutter_masked_text: ^0.8.0
  fluro: ^1.5.1
  provider: ^3.1.0+1
  http: ^0.12.0+2
  crypto: ^2.1.3
  flutter_styled_toast: ^1.2.0
  hive: ^1.1.1
  moor: ^2.1.0
  division: ^0.8.4+1
  built_value: ^7.0.0
  selection_menu: ^0.9.0
  path_provider: ^1.4.4
  url_launcher: ^5.2.3
  dio: ^3.0.7
  flutter_launcher_icons: ^0.7.4
  modal_progress_hud: ^0.1.3
  uuid: ^2.0.4
  overlay_container: ^0.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.1.0
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  
  assets:
    - resources/images/

  fonts:
    - family: Ubuntu     
      fonts:
        - asset: resources/fonts/Ubuntu-Light.ttf
          weight: 100
        - asset: resources/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: resources/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: resources/fonts/Ubuntu-Bold.ttf
          weight: 700
    - family: Ubuntu-Italic     
      fonts:
        - asset: resources/fonts/Ubuntu-LightItalic.ttf
          weight: 100
        - asset: resources/fonts/Ubuntu-Italic.ttf
          weight: 400
        - asset: resources/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
        - asset: resources/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
